### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by rrthomas** [EionRobb/purple-googlechat#2]
Backtrace [pidgin-backtrace.log](https://github.com/EionRobb/purple-googlechat/files/6740211/pidgin-backtrace.log)

**Comment by EionRobb** [comment]
> `warning: Source file is more recent than executable.` 

Are you able to re-`make` and `sudo make install` and get a new backtrace?

**Comment by rrthomas** [comment]
As far as I can tell, it's confused: the time stamp on the `.so` is later than that of all the source files.

**Comment by rrthomas** [comment]
Well, I did rebuild anyway, and now it's no longer crashing!!

**Comment by EionRobb** [comment]
Whew, glad that came right. Was thinking the next step would have been to remove all the one of logic. Maybe I will anyway though, the new(er) syntax for that in the code is dumb
