### ISSUE TITLE
Can Receive Messages but Cannot Send

### ISSUE THREAD

**Issue by fenderbender613** [EionRobb/purple-googlechat#22]
I am able to receive messages, but am not able to send them.  I am using the lastest Windows DLL from: https://eion.robbmob.com/libgooglechat.dll on Pidgin portable.

The message seems to be sent without error, but the recipient never receives it.  Looking at the debug log, it seems that the send action is encountering an error: "googlechat: Error from server: (Invalid HTTP response code (400))".  I have attached a debug log of the send action: [purple-debug.log](https://github.com/EionRobb/purple-googlechat/files/6957658/purple-debug.log)

Please let me know if I have a misconfiguration somewhere in my setup or help me understand what could be causing the issue that I am experiencing.  Thanks.

**Comment by EionRobb** [comment]
Is this the first time you've messaged this person?  If so, as a workaround, does disconnecting from the account and then reconnecting let you message them?

That "dfe.der.de" response type is weird - I wouldn't have expected to see a json response in a protobuf like that.  Hmm.

**Comment by BoFiS** [comment]
I've had almost the opposite experience a few times where my sent msgs are properly sent, but I don't get any replies, they all show up on my phone though.  Reconnecting resolves it, and it hasn't happened this week so far, but I suspect has to do with online status.

**Comment by fredtj** [comment]
same issue for me:

```
(08:44:10) googlechat: Error from server: (Invalid HTTP response code (400)) "["dfe.der.de",200011](2
dfe.der.deHR
ñÙžJË
```

first time messaging: yes for googlechat plugin, no for hangouts plugin
works after reconnect: no

**Comment by badjer2** [comment]
Pidgin 2.14.9 (libpurple 2.14.9), Windows 10, crated an account which imported data from old protocol, wuld get messages but my messages were not being sent. deleted the account, created it again, didnt import, same behaviour.

**Comment by badjer2** [comment]
with some testing i managed to figure out that this happens only in conversations where history is turned off. if you switch history on, messages go trough, when you turn it off they stop sending again

**Comment by ondrej-zary** [comment]
I have the same problem. purple-googlechat compiled from source.
(08:19:44) googlechat: Error from server: (Invalid HTTP response code (400)) "["dfe.der.de",200011](�2
dfe.der.deHR

**Comment by ondrej-zary** [comment]
Now I see what history badjer2 meant - the history in gmail web interface. Login to gmail, open a chat window and it must say "History is on" in the input box. If it says "History is off", click the 3 dots at the top right of the chat window and select "Turn on history".
