### ISSUE TITLE
Can't get OAuth Token

### ISSUE THREAD

**Issue by n0xa** [EionRobb/purple-googlechat#24]
I'm having a heck of a time getting my oauth token. I have multi-factor auth enabled, and generated an app-specific password to use for LibPurple (hoping to eventually use it with Finch, but using Pidgin so far). I have watched the video and can't find any cookie called oauth_code. I do web application security bug hunting occasionally, so I went so far as to fire up OWASP Zed Attack Proxy with a man-in-the-middle certificate on a test browser session, and logging all of my traffic as I signed out of my google account and logged back in. I have every single request, form POST, all cookie content and even the content of all of the HTML, CSS etc that was sent between my browser and Google while logging in and then going to gmail and opening a chat. At no point does the string of letters "oauth" (case insensitive) go across the wire, in any cookie or otherwise. What am I missing?

**Comment by EionRobb** [comment]
Just to check, you're following the URL in the description,  https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbU43SXh4QnpQczJVVFk2d3ExVVo5ZkdqcVBXUXxBQ3Jtc0tuZ1R5T1BNZzlmTE0yLS1acGJEMjJ5c0RxTnRpVTdaVi05b3NOZ1dtZFFQRFhXcDhYc3gyX3BjYm1MWVlOOWdUZUJiTnVLdEZzS3RPeVJSLXN5SHBkbHU4VnpoenU3NzlGQngwRVV5dnJCZ0E0NVl2NA&q=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fprogrammatic_auth%3Fhl%3Den%26scope%3Dhttps%253A%252F%252Fwww.google.com%252Faccounts%252FOAuthLogin%2Bhttps%253A%252F%252Fwww.googleapis.com%252Fauth%252Fuserinfo.email%26client_id%3D936475272427.apps.googleusercontent.com%26access_type%3Doffline%26delegated_client_id%3D183697946088-m3jnlsqshjhh5lbvg05k46q1k4qqtrgn.apps.googleusercontent.com%26top_level_cookie%3D1 
and getting to the "Please wait a moment..." screen?

**Comment by n0xa** [comment]
Wow. Somehow I missed that and thought the video was just showing signing in via accounts.google.com. I re-read that description 10 times and somehow missed the URL. Thanks, that worked. Thanks for getting back to me.
[dies a little]

**Comment by EionRobb** [comment]
Nah, all good.  You're not the only one :)

I'm hoping to make that lots easier with a new youtube video and with a browser window for sign in, when I can find the time :)

**Comment by djkraven** [comment]
The link is no longer valid. Do you have an update on this process?

**Comment by Jhojoyms** [comment]
Thanks Sir, Do you have an update on this process? 

> Just to check, you're following the URL in the description, https://accounts.google.com/o/oauth2/programmatic_auth?hl=en&scope=https%3A%2F%2Fwww.google.com%2Faccounts%2FOAuthLogin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&client_id=936475272427.apps.googleusercontent.com&access_type=offline&delegated_client_id=183697946088-m3jnlsqshjhh5lbvg05k46q1k4qqtrgn.apps.googleusercontent.com&top_level_cookie=1 and getting to the "Please wait a moment..." screen?
