### ISSUE TITLE
Bad Request after creating account

### ISSUE THREAD

**Issue by mfauvain** [EionRobb/purple-googlechat#32]
Hi, followed the procedure to get the Oauth token, but cannot manage to get it to work. Auth fails and then I have 'Bad Request'. any idea?

**Comment by EionRobb** [comment]
Off the top of my head, I'm not sure what that could be caused by.

Are you able to try to reconnect after opening the debug log at Help->Debug Window, and pasting into the issue here?  (Please do be careful before pasting to remove any mention of access/refresh/uberauth tokens)

**Comment by mfauvain** [comment]
Very weird, to check if the token was working with the old Hangout plugin, I re-created the pidgin hangout account (same google account) and used the token. did not work either. then deleted it. closed pidgin, reopen it... and voila... google chat plugin connects.
I suspect it has to do with the gnome keyring plugin. not sure. but it works and this made the day. going to bed now. thx!

**Comment by EionRobb** [comment]
Yay, glad to hear you got it going :)
