### ISSUE TITLE
Fedora dependencies for compiling: protobuf-c-compiler

### ISSUE THREAD

**Issue by adatum** [EionRobb/purple-googlechat#43]
The README shows the list of dependencies (thanks for including this!) for Fedora as:

```
json-glib-devel libpurple-devel glib2-devel libpurple-devel protobuf-c-devel protobuf-c-compiler-devel
```

but there is no such package as `protobuf-c-compiler-devel`. 

`protobuf-c-compiler` does exist, and with it installed, `purple-googlechat` compiles and installs without issues.

---

Thanks for this plugin. I just installed it due to getting this email from Google:

> **Your third-party app will stop working with Google Talk on 2022-06-15**

> You're receiving this email because our records show you may have recently used a third-party app to connect to Google Talk.
> 
> As we announced in 2017, we are winding down Google Talk. On 2022-06-15, we will end our support for third-party apps (including Pidgin and Gajim). Visit the Help Center for more details.
>  
> To  continue chatting with your contacts, we recommend using Google Chat.  Google Chat offers enhanced features like Spaces, which allow you to  more easily plan with others, share and collaborate on files, and assign  tasks. It also includes accessibility features like screen reader  support and the same strong phishing protections we built in Gmail.
>  
> You  can use the same account that you used with Google Talk to sign in to  Google Chat. Google Chat can be accessed on the web and mobile, or added  to your Gmail inbox to enable collaboration in one place. Check out the  Help Center for information on exporting your data and hiding or deleting your conversations.
>  
> Sincerely,
>  
> The Google Talk Team

**Comment by EionRobb** [comment]
Thanks for the info :)

I've updated the readme, if you could check it looks ok now?
