### ISSUE TITLE
No icon is shown for protocol

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-googlechat#44]
Protocol has no icon

**Comment by nxths** [comment]
If you didn't install through the `Makefile` you'll need to manually copy+rename the images as in https://github.com/EionRobb/purple-googlechat/blob/master/Makefile#L116, are those files in your pidgin install directory?

**Comment by alexolog** [comment]
I am running Pidgin on Windows, so no, I used the provided DLLs.
Thanks for the tip, I will copy the PNGs.

**Comment by EionRobb** [comment]
Ah. Yeah, sorry. The plugin can't automatically add icons in to the UI without an installer of some kind. 

Maybe i should make an installer...

**Comment by poadb** [comment]
Any progress update on that installer for Windows? Or maybe some steps to get the 3 dll's working ourselves?

**Comment by alexolog** [comment]
Just copy them into the correct folders as per the instructions, rename and copy the PNGs as mentioned above, restart Pidgin, and it should work

**Comment by EionRobb** [comment]
I've updated the readme to try help clarify that https://github.com/EionRobb/purple-googlechat/blob/master/README.md#windows

**Comment by alexolog** [comment]
As an alternative to an installer, a zip file with all the DLLs and images in subdirectories can be used.
