### ISSUE TITLE
Please explain how to input oauth token in bitlbee

### ISSUE THREAD

**Issue by noahfriedman** [EionRobb/purple-googlechat#47]
The FAQ regarding bitlbee in the old hangouts plugin wiki was vague about how one actually did this.  You can't store the oauth token as a password, evidently, but there is no other "popup" a la pidgin to input credentials by any other means using bitlbee.

Is there some reason why the initial token cannot be stored as a password?  I understand this will occasionally have to be reset; that's fine.

**Comment by EionRobb** [comment]
Thanks for the feedback!  I don't use bitlbee myself so I wasn't aware of the delays.. that sounds a bit confusing.  I've updated the readme to give hints to the next person who stumbles across the same problem https://github.com/EionRobb/purple-googlechat/blob/master/README.md#bitlbee

Do those directions sound OK?

**Comment by noahfriedman** [comment]
Sorry I missed notification for your comment.  Yes, that looks good  Thanks!

**Comment by ronansalmon** [comment]
@EionRobb I've seen this as well. Could you update the Readme with what @noahfriedman was saying  :
->
If you're using this plugin with bitlbee, authentication might be a little confusing. After you follow the prompts, you should get a DM from a purple_request_0 user asking for the token. Once done, you need to turn off and on your account to get it working. You can also set the token as the password on the account, if you don't see the DM.

Thanks for this plugin !
