### ISSUE TITLE
Adium support?

### ISSUE THREAD

**Issue by dhouck** [EionRobb/purple-googlechat#54]
Is there any chance you could add support for Adium?  I know it uses libpurple and I saw you mention offhand in response to another issue that it should work, but there are no instructions for it and it looks like the Makefile assumes Pidgin.

**Comment by EionRobb** [comment]
Unfortunately, for a libpurple plugin to work with Adium, it needs to be wrapped up into an Adium plugin, they don't just work straight out of the box.  eg you can see that @tripplet has done that with a few plugins with https://github.com/tripplet?tab=repositories&q=adium&type=&language=&sort=

Sadly there's not a generic Adium plugin that could load in any libpurple plugin without needing it to be individually wrapped up.  That would be amazing if there was.
