### ISSUE TITLE
Manjaro/arch

### ISSUE THREAD

**Issue by Steven11q** [EionRobb/purple-googlechat#60]
Hi, When trying to install the dependencies with pacman I encountered issues. Does this plugin support arch, and if so how would I go about installing it?
Thanks!

**Comment by EionRobb** [comment]
What commands did you run and what issues were there?
As a fallback, you can always compile using https://github.com/EionRobb/purple-googlechat#compiling

**Comment by Steven11q** [comment]
I was able to install from the application store, thank you.

**Comment by Steven11q** [comment]
It successfully installed, but it isent appearing in the plugin list. What should I do?

**Comment by EionRobb** [comment]
Protocol plugins, such as this one, don't appear in the Tools->Plugins list, they only appear in the dropdown of protocols when you add a new account from the Accounts->Add Account screen

**Comment by Steven11q** [comment]
Ah! it seems I needed to restart my computer to get it to show up, but I successfully added my account! Now my messages are whited out but I think that issue is already open. Thank you for the help!
