### ISSUE TITLE
Malformed auth code

### ISSUE THREAD

**Issue by bodqhrohro** [EionRobb/purple-googlechat#7]
I just reused the code from prpl-hangouts. Should I obtain a new one? Or maybe activate Google Chat somewhere in the web first?

Also, implicitly opening a YouTube link in a default browser is a bit saucy, as users may prefer to watch it other way. It also may remain unnoticed if the xdg schema is broken and points to no visible outcome, and makes no sense on servers. ~~May the link be displayed somewhere as a fallback, at least?~~ oh, it's actually displayed in the dialog ;D — though ain't copyable.

**Comment by EionRobb** [comment]
Yep, you need to obtain a new one.  You could also edit ~/.purple/accounts.xml (while Pidgin isn't running) and copy over the <password> from your old hangouts account to the new googlechat one

**Comment by bodqhrohro** [comment]
That worked, thanks.
Why wouldn't the prpl itself save the password?

**Comment by EionRobb** [comment]
The codes that the 'please wait a moment' pages provide only work as a once-off

I've added in a thingee to convert existing Hangouts accounts over in https://github.com/EionRobb/purple-googlechat/commit/4f337e24d877e8d23435c61e06ac18fa2ae9b841
