### ISSUE TITLE
Windows plugin no longer connects

### ISSUE THREAD

**Issue by Ikjerang** [EionRobb/purple-googlechat#73]
As of today attempts to connect to Google Chat return with "Invalid response". It disconnected while active, gave replacing the .dll with a fresh download a try, no luck.

**Comment by alexolog** [comment]
No issues here

**Comment by Ikjerang** [comment]
Apparently the issue was network related, never had that happen that way before. Modem got reset and suddenly a ton of messages came in. It was a me problem, yaaay~
