### ISSUE TITLE
Feature: copy over hangouts account settings

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-googlechat#8]
Add a check on first launch to ask whether to copy over the prpl-hangouts accounts to prpl-googlechat accounts.  Just the password and buddy list, maybe migrate logs later?

**Comment by EionRobb** [comment]
Done in https://github.com/EionRobb/purple-googlechat/commit/4f337e24d877e8d23435c61e06ac18fa2ae9b841

**Comment by zyphlar** [comment]
This worked seamlessly for 2/3 of my accounts, I had to do the oauth copy-paste procedure for my other account.

**Comment by BoFiS** [comment]
Works great, however, if you accidentally click no then I'm not sure how to trigger it again besides reverting my prefs.xml file back quickly and reopening Pidgin

**Comment by zyphlar** [comment]
Ah upon quit and reopen, I had to copy the oauth code for the other 2 of 3 accounts. Interestingly they worked just fine until I quit pidgin.

**Comment by EionRobb** [comment]
Hmm... it looks like the refresh token isn't saving into the <password> field of accounts.xml - its just existing in memory

**Comment by EionRobb** [comment]
Ok, I'm a dingus.  If you had downloaded the dll then it was from one commit previous where I didn't mark the password to be saved.  In my haste of fixing it I hadn't pushed a new dll to the website ;(

**Comment by EionRobb** [comment]
Oh, all because I didn't push the commit.  Was solved in https://github.com/EionRobb/purple-googlechat/commit/6fb2b7c4529e578fb740c4a8b555ba1081599160

**Comment by zyphlar** [comment]
I compiled from source but yeah if it wasn't pushed as of my first comment above then that'd do it
