### ISSUE TITLE
Image sending doesn't fully work

### ISSUE THREAD

**Issue by zyphlar** [EionRobb/purple-googlechat#9]
The recipient gets `<IMG ID="30">` instead of the image. Receiving seems to work halfway decently however. (One of two images appeared, that I sent from the web client to another person)

**Comment by EionRobb** [comment]
Ah yeah, sorry.  Should have turned off the UI flag that lets Pidgin send bold/italics formatting, as well as images inline.  That code couldn't be brought over from the Hangouts plugin and has to be rewritten.

GoogleChat has a completely different way of attaching images and formatting to a message, where the message needs to be sent in plain text with some 'annotations' to say `"heres some plain text` along with `"this part of the plain text should be bold" or "this part should have an image"` (Hangouts would do it more like xml and do it all in one in blocks `["this part is bold","this part is not"]`)

**Comment by BoFiS** [comment]
Also just pasting a URL seems to get messed up sometimes, such as copying the image address from a photo on Facebook, once it's pasted/sent through this plugin somehow the extra data on the end is truncated and the link no longer works to show the image, even if what I'm copying/pasting works in a private window.

**Comment by EionRobb** [comment]
I've disabled image sending for now, since the plugin isn't authenticating with the image server properly yet, so it's not pushing the image to the server

I have fixed pasting urls though @BoFiS 

In terms of receiving images, there seem to be a multitude of ways of sending/receiving them (saved to Google Drive with a direct link, uploaded to a google image server with an indirect link, just a link to an image), which depends on the client sending the image.  @zyphlar could you keep track of which sending clients you're able to receive images from and which ones fail?

**Comment by zyphlar** [comment]
@EionRobb thanks for being so responsive. Here's the results of my testing with the latest code from today.

- uploaded a video using the hangouts app for android:
  - "I shared a video attachment using the classic Hangouts (https://hangouts.google.com)."

- uploaded a photo using the hangouts app for android:
  - blank message for sender and receiver, despite working in hangouts

- uploaded a photo using pidgin:
  - "works" locally but does not actually upload (blank message for receiver, nothing inside hangouts app)

- uploaded a photo using hangouts.google.com webapp (which might be the "google drive" method you're describing since it uses a similar sort of upload and server-side browsing GUI? though i don't see any things actually saved in Drive?):
  - blank message for sender and receiver, despite working in hangouts

here is the pidgin debug log for receiving the photo from the hangouts.google.com webapp, redacted with 00000s:

```
(17:00:35) googlechat: {
	"group_id" : {
		"space_id" : null,
		"dm_id" : {
			"dm_id" : "toZ00000AAE"
		}
	},
	"type" : "MESSAGE_UPDATED",
	"body" : {
		"message_posted" : {
			"message" : {
				"id" : {
					"parent_id" : {
						"topic_id" : {
							"topic_id" : "4vy00000bOo",
							"group_id" : {
								"space_id" : null,
								"dm_id" : {
									"dm_id" : "toZ00000AAE"
								}
							}
						}
					},
					"message_id" : "4vy00000bOo"
				},
				"creator" : {
					"user_id" : {
						"id" : "107000000000000000615",
						"type" : null
					},
					"name" : null,
					"avatar_url" : null,
					"email" : null,
					"first_name" : null,
					"last_name" : null,
					"deleted" : null,
					"is_anonymous" : null,
					"gender" : null,
					"block_relationship" : null
				},
				"create_time" : 1620000000000911,
				"last_update_time" : 1620000000000598,
				"last_reply_time" : null,
				"last_view_time" : null,
				"last_mention_time" : null,
				"delete_time" : null,
				"num_unread_replies" : null,
				"text_body" : "",
				"annotations" : [
					{
						"type" : "URL",
						"start_index" : null,
						"length" : null,
						"drive_metadata" : null,
						"url_metadata" : {
							"title" : null,
							"snippet" : null,
							"image_url" : "https://chat.google.com/api/get_hangouts_attachment_url?url_type=FIFE_URL&attachment_token=AOe0000000000000000000000000000redacted268characters0000000000000000000000000000000000000000008qo3Q%3D%3D&width=241&height=233",
							"image_height" : "233",
							"image_width" : "241",
							"url" : {
								"url" : "https://www.google.com/url?q=https://chat.google.com/api/get_hangouts_attachment_url?url_type%3DFIFE_URL%26attachment_token%3DA0000000000000000000000000000redacted268characters0000000000000000000000000000000000000000008qo3Q%253D%253D%26width%3D241%26height%3D233&source=chat&ust=1620000000081000&usg=AFQjC0000000000000000000000000jw3w"
							},
							"domain" : null,
							"should_not_render" : null,
							"int_image_height" : 233,
							"int_image_width" : 241,
							"mime_type" : "image/*",
							"gws_url" : {
								"url" : "https://www.google.com/url?q=https://chat.google.com/api/get_hangouts_attachment_url?url_type%3DFIFE_URL%26attachment_token%3DA0000000000000000000000000000redacted268characters0000000000000000000000000000000000000000008qo3Q%253D%253D%26width%3D241%26height%3D233&source=chat&ust=1620000000081000&usg=AFQjC0000000000000000000000000jw3w"
							},
							"redirect_url" : {
								"url" : "https://chat.google.com/api/get_redirect_url?url_redirect_token=AJW000000000000000000000000000000000000000000000000000000000000000000000000000000redacted578characters000000000000000000000000000000000000000000000000000000000000000iag%3D%3D"
							},
							"gws_url_expiration_timestamp" : 1620000000081000
						},
						"format_metadata" : null,
						"local_id" : null,
						"upload_metadata" : null,
						"server_invalidated" : null,
						"unique_id" : null,
						"chip_render_type" : "RENDER"
					}
				],
				"last_reply" : null,
				"sort_time" : null,
				"local_id" : "HANGOUTS-567000000713:9PT0000000000000000Fwy:Ugy0000000000000000000000000000ODA",
				"attachments" : [
				],
				"last_edit_time" : null,
				"message_state" : "GROUP_VISIBLE",
				"reactions" : [
				],
				"message_type" : "USER_MESSAGE",
				"creator_membership" : null
			},
			"last_message_in_topic_time" : 0,
			"prev_revision_time" : 0,
			"is_head_message" : false
		},
		"event_type" : "MESSAGE_UPDATED",
		"membership_changed" : null,
		"trace_id" : null,
		"user_status_updated_event" : null,
		"typing_state_changed_event" : null
	},
	"user_id" : null,
	"bodies" : [
	]
}
(17:00:35) http: Request 0x5560000005a0 performed successfully.
(17:00:35) http: Request 0x5560000009f0 performed successfully.
(17:00:35) http: Request 0x556000000e80 performed successfully.
```

**Comment by EionRobb** [comment]
Thanks for the debug log, @zyphlar - I tested sending from various Google Chat clients (iOS, Android, Web), but hadn't tried with Hangouts yet which looks like it behaves differently to all of them.

I think the Hangouts case should be handled by https://github.com/EionRobb/purple-googlechat/commit/2226f0ea5fc03be514979fa591df24c802d3d6c5

**Comment by zyphlar** [comment]
Somehow through all of this I didn't fully process that chat.google.com / Google Chat was a separate thing I could download or use lol.

Via Google Chat, purple-googlechat currently receives images fine but has trouble sending them.

Interestingly Google Chat seems to suck at sending video. I uploaded an MP4 file from the Android app and not only does it display as a second-party file attachment in the native clients, but it doesn't appear at all in Pidgin.

**Comment by EionRobb** [comment]
@zyphlar yeah, there's lots of different ways that different types of data get sent https://github.com/EionRobb/purple-googlechat/blob/master/googlechat.proto#L955  video separate to images separate to google drive separate to urls linking to images - and then even within each of those there can be two or three different ways they end up coming through (an ID that needs to be looked up, or a thumbnail url, or a regular image url).  I need to build in options for each into the plugin on a case-by-case

**Comment by zyphlar** [comment]
#18 addresses the "Maybe linking the "full image" to Drive would be useful i.e. to get the original file instead of preview" part.

Looks like the main remaining task on this issue is regular old image sending from Pidgin, receipt seems pretty good.

**Comment by EionRobb** [comment]
Yay! Got image sending working :)
